"""create table participants

Revision ID: 493e5bb8f1d5
Revises: be71675d0fac
Create Date: 2026-09-26 14:38:42.232189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '493e5bb8f1d5'
down_revision: Union[str, Sequence[str], None] = 'be71675d0fac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_token', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['table_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_participants_public_token'), 'table_participants', ['public_token'], unique=True)
    op.create_index(op.f('ix_table_participants_session_id'), 'table_participants', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_participants_session_id'), table_name='table_participants')
    op.drop_index(op.f('ix_table_participants_public_token'), table_name='table_participants')
    op.drop_table('table_participants')
    # ### end Alembic commands ###
