"""create restaurant members

Revision ID: 587500e03b02
Revises: 94764350be10
Create Date: 2026-07-14 14:41:34.803915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '587500e03b02'
down_revision: Union[str, Sequence[str], None] = '94764350be10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('auth_user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='admin', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'admin', 'staff')", name='ck_restaurant_members_valid_role'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'auth_user_id', name='uq_restaurant_members_restaurant_user')
    )
    op.create_index(op.f('ix_restaurant_members_auth_user_id'), 'restaurant_members', ['auth_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurant_members_auth_user_id'), table_name='restaurant_members')
    op.drop_table('restaurant_members')
    # ### end Alembic commands ###
