"""create shared cart items

Revision ID: 6a0c19b64864
Revises: 493e5bb8f1d5
Create Date: 2026-09-26 14:48:19.693596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a0c19b64864'
down_revision: Union[str, Sequence[str], None] = '493e5bb8f1d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_cart_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('menu_item_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_shared_cart_quantity_positive'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['table_participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['table_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'participant_id', 'menu_item_id', name='uq_shared_cart_participant_item')
    )
    op.create_index(op.f('ix_shared_cart_items_menu_item_id'), 'shared_cart_items', ['menu_item_id'], unique=False)
    op.create_index(op.f('ix_shared_cart_items_participant_id'), 'shared_cart_items', ['participant_id'], unique=False)
    op.create_index(op.f('ix_shared_cart_items_session_id'), 'shared_cart_items', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shared_cart_items_session_id'), table_name='shared_cart_items')
    op.drop_index(op.f('ix_shared_cart_items_participant_id'), table_name='shared_cart_items')
    op.drop_index(op.f('ix_shared_cart_items_menu_item_id'), table_name='shared_cart_items')
    op.drop_table('shared_cart_items')
    # ### end Alembic commands ###
