"""create staff requests

Revision ID: 6a64b412609b
Revises: eebdde697ba5
Create Date: 2026-09-24 19:21:55.524691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a64b412609b'
down_revision: Union[str, Sequence[str], None] = 'eebdde697ba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_token', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('new', 'accepted', 'completed')", name='ck_staff_request_status'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['restaurant_tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_requests_public_token'), 'staff_requests', ['public_token'], unique=True)
    op.create_index(op.f('ix_staff_requests_restaurant_id'), 'staff_requests', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_staff_requests_table_id'), 'staff_requests', ['table_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_requests_table_id'), table_name='staff_requests')
    op.drop_index(op.f('ix_staff_requests_restaurant_id'), table_name='staff_requests')
    op.drop_index(op.f('ix_staff_requests_public_token'), table_name='staff_requests')
    op.drop_table('staff_requests')
    # ### end Alembic commands ###
