"""create feedback tables

Revision ID: b51d6499df41
Revises: 7bf7dff77538
Create Date: 2026-09-21 14:17:09.441666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b51d6499df41'
down_revision: Union[str, Sequence[str], None] = '7bf7dff77538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('overall_rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('overall_rating >= 1 AND overall_rating <= 5', name='ck_feedback_overall_rating'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_order_id'), 'feedback', ['order_id'], unique=True)
    op.create_table('feedback_item_ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feedback_id', sa.UUID(), nullable=False),
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_feedback_item_rating'),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feedback_id', 'order_item_id', name='uq_feedback_order_item')
    )
    op.create_index(op.f('ix_feedback_item_ratings_feedback_id'), 'feedback_item_ratings', ['feedback_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_item_ratings_feedback_id'), table_name='feedback_item_ratings')
    op.drop_table('feedback_item_ratings')
    op.drop_index(op.f('ix_feedback_order_id'), table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###
