"""create table sessions

Revision ID: be71675d0fac
Revises: 6a64b412609b
Create Date: 2026-09-26 14:27:05.531060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be71675d0fac'
down_revision: Union[str, Sequence[str], None] = '6a64b412609b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_token', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active', 'closed')", name='ck_table_session_status'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['restaurant_tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_sessions_public_token'), 'table_sessions', ['public_token'], unique=True)
    op.create_index(op.f('ix_table_sessions_restaurant_id'), 'table_sessions', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_table_sessions_table_id'), 'table_sessions', ['table_id'], unique=False)
    op.create_index(
        "uq_table_sessions_active_table",
        "table_sessions",
        ["table_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_sessions_table_id'), table_name='table_sessions')
    op.drop_index(op.f('ix_table_sessions_restaurant_id'), table_name='table_sessions')
    op.drop_index(op.f('ix_table_sessions_public_token'), table_name='table_sessions')
    op.drop_index(
        "uq_table_sessions_active_table",
        table_name="table_sessions",
    )
    op.drop_table('table_sessions')
    # ### end Alembic commands ###
