"""add public flag to feedback

Revision ID: eebdde697ba5
Revises: b51d6499df41
Create Date: 2026-09-23 20:16:22.744348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eebdde697ba5'
down_revision: Union[str, Sequence[str], None] = 'b51d6499df41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'is_public')
    # ### end Alembic commands ###
